remote_theme: pages-themes/hacker@v0.2.0
# pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme

title: Baldesion Arsenal Primer

description: A short introduction of the Baldesion Arsenal raid, tailored to the Light Datacentre tactics

show_downloads: false

markdown: kramdown
